### ISSUE TITLE
Pickle problem

### ISSUE THREAD

**Issue by sanglinwei** [locuslab/DC3#1]
Some important functions are serialized in pickle form, and I wonder if the authors can go detail into the pickle part.

**Comment by priyald17** [comment]
The details of all functions that are included as part of serialized objects are included here: https://github.com/locuslab/DC3/blob/main/utils.py

Is that what you meant, or were there other details you are looking for?

**Comment by sanglinwei** [comment]
Yeah, Got it. Thank you for your kindness.
